djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("hostel.urls"))
]

hostel/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.glavn),
    path("reg", views.reg),
    path("vhod", views.vhod),
    path("bron", views.bron),
    path("room/<int:roomid>", views.rooms),
    path("nomera", views.nomera)
]

hostel/models.py
from django import forms
from django.db import models


class User(models.Model):
    user_name = models.CharField("ИМЯ", max_length=50)
    email = models.CharField("ПОЧТА", max_length=50)
    password = models.CharField("ПАРОЛЬ", max_length=50)

    def __str__(self):
        return self.user_name

    class Meta:
        verbose_name = 'профиль пользователя'
        verbose_name_plural = 'Зарегистрированные пользователи'


class Rooms(models.Model):
    number = models.CharField("НОМЕР", max_length=2)
    today_status = models.CharField("СЕГОДНЯ", max_length=8)
    tomorrow_status = models.CharField("ЗАВТРА", max_length=8)

    def __str__(self):
        return self.number

    class Meta:
        verbose_name = 'номер'
        verbose_name_plural = 'Номера'

hostel/forms.py
from .models import User
from django.forms import ModelForm, TextInput, EmailInput, PasswordInput


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['user_name', 'email', 'password']
        widgets = {
            'user_name': TextInput(attrs={
                "type": "text",
            }),
            'email': EmailInput(attrs={
                "type": "email",
            }),
            'password': PasswordInput(attrs={
                "type": "password",
                "minlength": 6
            })
        }

hostel/views.py
from django.shortcuts import render, redirect
from .models import User, Rooms
from .forms import UserForm


def glavn(request):
    return render(request, 'hostel/Главная.html')


def vhod(request):
    allusers = User.objects.all()
    if request.method == 'POST':
        for el in allusers:
            if el.user_name == request.POST.get('user_name') and el.password == request.POST.get('password'):
                return redirect('/bron')

    form = UserForm()
    return render(request, 'hostel/Вход.html', {"allusers": allusers, "form": form})


def reg(request):
    allusers = User.objects.all()
    message = None

    if request.method == 'POST':
        email = request.POST.get('email')
        if allusers.filter(email=email).exists():
            message = "Пользователь с таким логином уже существует!"
        else:
            form = UserForm(request.POST)
            if form.is_valid():
                form.save()
                message = "Регистрация прошла успешно!!"

    form = UserForm()
    return render(request, 'hostel/Регистрация.html', {"allusers": allusers, "form": form, "message": message})


def bron(request):
    allrooms = Rooms.objects.all()
    return render(request, 'hostel/Бронирование.html', {'allrooms': allrooms})


def rooms(request, roomid):
    today_room_is_free = True
    tomorrow_room_is_free = True
    allrooms = Rooms.objects.all()
    for el in allrooms:
        if el.number == str(roomid):
            if el.today_status != "СВОБОДЕН":
                today_room_is_free = False
            if el.tomorrow_status != "СВОБОДЕН":
                tomorrow_room_is_free = False
        if request.method == "POST":
            if "today" in request.POST:
                el = Rooms.objects.get(number=str(roomid))
                el.today_status = "ЗАНЯТ"
            if "tomorrow" in request.POST:
                el = Rooms.objects.get(number=str(roomid))
                el.tomorrow_status = "ЗАНЯТ"
            el.save()
            return redirect(request.path)
    return render(request, f'hostel/room{roomid}.html', {'today_room_is_free': today_room_is_free,
                                                         'tomorrow_room_is_free': tomorrow_room_is_free,
                                                         'roomid': roomid})

def nomera(request):
    return render(request, 'hostel/Номера.html')

hostel/templates/hostel/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

hostel/templates/hostel/baseroom.html
{% load static %}

<!DOCTYPE html>
<html lang="ru ">

<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  <style>
    body {
      background: #b6d5f6 fixed;
      background-size: cover;
    }

    .inline-block {
            display: inline-block;
        }

    .container {
      display: flex;
      justify-content: space-between;
      height: 350px;
      padding: 20px;
    }

    .image {
      width: 50%;
    }

    .description {
        width: 50%;
        text-align: left;
        color: #fff;
        font-size: 24px;
    }

    .bronbutt_active {
      padding: 10px 20px; /* Задает внутренний отступ кнопки */
      font-size: 16px; /* Задает размер шрифта кнопки */
      border-radius: 8px; /*Задает скругленные углы кнопки */
      color: #ffffff; /* Задает цвет текста кнопки */
      background-color: #4287f5; /* Задает цвет фона кнопки */
      border: 2px solid #4287f5; /* Задает стиль границы кнопки */
    }

    button.bronbutt_active:hover {
        background-color: #42cbf5;
    }
    button.bronbutt_active:active {
        background-color: #4287f5;
    }

    .bronbutt_disabled {
      padding: 10px 20px; /* Задает внутренний отступ кнопки */
      font-size: 16px; /* Задает размер шрифта кнопки */
      border-radius: 8px; /*Задает скругленные углы кнопки */
      color: #ffffff; /* Задает цвет текста кнопки */
      background-color: rgba(241, 9, 9, 0.51); /* Задает цвет фона кнопки */
      border: 2px solid rgba(241, 9, 9, 0.51); /* Задает стиль границы кнопки */
    }

    a:link{color: #224588FF; text-decoration: none}
    a:visited{color: #224588FF;}

    a.menu-link:hover {
        background-color: #b6d5f6;
        border-radius: 3px;
    }
    a.menu-link:active {
        background-color: #6c90d3;
    }

  </style>
<script>
    function showMessage() {
      alert("Номер успешно забронирован!");
    }
</script>
</head>

<body>
<header style="background-color: #d8ebff; border: 1px solid rgba(39,113,225,0.46); border-radius: 8px;">
    <div class="inline-block" style="position: relative; top: 6px; left: 10px">
        <img src="{% static 'hostel/images/vodoley.png' %}" height="100px" style="border-radius: 8px;">
    </div>


<h1 style="text-align: center; color: #224588FF; margin-top: -80px; font-family: Arial, sans-serif">ВОДОЛЕЙ</h1>

<div class="inline-block" style="margin-top: 5px; font-family: Arial, sans-serif">
  <a href="/" class="menu-link" style="margin-left: 550px;">Главная</a>
  <a href="/nomera" class="menu-link" >Номера</a>
  <a href="/vhod" class="menu-link" >Бронирование</a>
  <a href="/reg" class="menu-link" >Регистрация</a>
</div>

<hr color='5da4fc'>
</header>

<h2 align="center" style="color: #4287f5">{% block numberofroom %}{% endblock %}</h2>

<div class="container">
<div class="image">
  {% block source %}{% endblock %}
</div>

<div class="description">
  {% block description %}{% endblock %}
</div>
</div>

{#<div style="position: relative; left: 845px; bottom: 50px;  color: rgba(241, 9, 9, 0.51)">#}
{#  {% if room_is_free == False %}<h2>Занят</h2>{% endif %}#}
{#</div>#}

{% if today_room_is_free == True %}
    <form  method="post">
    {% csrf_token %}
    <button name="today" type="submit" class=bronbutt_active onclick="showMessage()" style="position: relative; left: 750px; top: -30px">Сегодня: Забронировать</button>
    </form>
{% else %}
    <button class=bronbutt_disabled style="position: relative; left: 750px; top: -30px">Сегодня: Занят</button>
{% endif %}
<br>
{% if tomorrow_room_is_free == True %}
    <form  method="post">
    {% csrf_token %}
    <button name="tomorrow" type="submit" class=bronbutt_active onclick="showMessage()" style="position: relative; left: 750px; top: -20px">Завтра: Забронировать</button>
    </form>
{% else %}
    <button class=bronbutt_disabled style="position: relative; left: 750px; top: -20px">Завтра: Занят</button>
{% endif %}

</body>
</html>

hostel/templates/hostel/room1.html
{% extends 'hostel/baseroom.html' %}
{% load static %}

{% block title %}
    Номер 1
{% endblock %}

{% block numberofroom %}
    Номер 1
{% endblock %}

{% block source %}
    <img src="{% static 'hostel/images/standart_room-1.jpg' %}" alt="Номер 9" style="height: 450px; border: 1px solid #1460af; border-radius: 8px;">
{% endblock %}

{% block description %}
    Добро пожаловать в наш стандартный номер! Это просторное и уютное помещение, созданное для вашего комфорта и отдыха.
    В стандартном номере вы найдете все необходимое для приятного пребывания.
    У нас предусмотрены удобная кровать, современная ванная комната, оснащенная всеми необходимыми удобствами,
    а также рабочее пространство для выполнения деловых задач или планирования маршрута вашего отдыха.
    Мы предлагаем бесплатный Wi-Fi, телевизор с широким выбором каналов и доступ к прачечной услуге.
    Цена/сутки: 1500 рублей.
{% endblock %}

hostel/templates/hostel/room10.html
{% extends 'hostel/baseroom.html' %}
{% load static %}

{% block title %}
    Номер 10
{% endblock %}

{% block numberofroom %}
    Номер 10
{% endblock %}

{% block source %}
    <img src="{% static 'hostel/images/luks.jpg' %}" alt="Номер 10" style="height: 480px; position: relative; top: -20px; left: 10px; border: 1px solid #1460af; border-radius: 8px;">
{% endblock %}

{% block description %}
    Просторный и изысканно оформленный номер Люкс предлагает максимальный комфорт и роскошь.
    С его площадью в 40 квадратных метров, он станет идеальным выбором для тех, кто ищет уют
    и элегантность во время пребывания. В номере Люкс вы найдете удобную кровать размера King или Queen,
    отдельную гостиную зону с комфортными креслами, и просторную ванную комнату с джакузи и отдельным душем.
    Дополнительные удобства в номере включают бесплатный Wi-Fi, телевизор с плоским экраном, кондиционер,
    мини-бар, сейф и пресс для брюк. В номере Люкс гарантированы роскошь, комфорт и незабываемый отдых.
    Цена/сутки: 3500 рублей.

{% endblock %}

hostel/templates/hostel/room3.html
{% extends 'hostel/baseroom.html' %}
{% load static %}

{% block title %}
    Номер 3
{% endblock %}

{% block numberofroom %}
    Номер 3
{% endblock %}

{% block source %}
    <img src="{% static 'hostel/images/standart_room-1.jpg' %}" alt="Номер 9" style="height: 450px; border: 1px solid #1460af; border-radius: 8px;">
{% endblock %}

{% block description %}
    Добро пожаловать в наш стандартный номер! Это просторное и уютное помещение, созданное для вашего комфорта и отдыха.
    В стандартном номере вы найдете все необходимое для приятного пребывания.
    У нас предусмотрены удобная кровать, современная ванная комната, оснащенная всеми необходимыми удобствами,
    а также рабочее пространство для выполнения деловых задач или планирования маршрута вашего отдыха.
    Мы предлагаем бесплатный Wi-Fi, телевизор с широким выбором каналов и доступ к прачечной услуге.
    Цена/сутки: 1500 рублей.
{% endblock %}

hostel/templates/hostel/room4.html
{% extends 'hostel/baseroom.html' %}
{% load static %}

{% block title %}
    Номер 4
{% endblock %}

{% block numberofroom %}
    Номер 4
{% endblock %}

{% block source %}
    <img src="{% static 'hostel/images/standart_room-1.jpg' %}" alt="Номер 9" style="height: 450px; border: 1px solid #1460af; border-radius: 8px;">
{% endblock %}

{% block description %}
    Добро пожаловать в наш стандартный номер! Это просторное и уютное помещение, созданное для вашего комфорта и отдыха.
    В стандартном номере вы найдете все необходимое для приятного пребывания.
    У нас предусмотрены удобная кровать, современная ванная комната, оснащенная всеми необходимыми удобствами,
    а также рабочее пространство для выполнения деловых задач или планирования маршрута вашего отдыха.
    Мы предлагаем бесплатный Wi-Fi, телевизор с широким выбором каналов и доступ к прачечной услуге.
    Цена/сутки: 1500 рублей.
{% endblock %}

hostel/templates/hostel/room5.html
{% extends 'hostel/baseroom.html' %}
{% load static %}

{% block title %}
    Номер 5
{% endblock %}

{% block numberofroom %}
    Номер 5
{% endblock %}

{% block source %}
    <img src="{% static 'hostel/images/standart_room-1.jpg' %}" alt="Номер 9" style="height: 450px; border: 1px solid #1460af; border-radius: 8px;">
{% endblock %}

{% block description %}
    Добро пожаловать в наш стандартный номер! Это просторное и уютное помещение, созданное для вашего комфорта и отдыха.
    В стандартном номере вы найдете все необходимое для приятного пребывания.
    У нас предусмотрены удобная кровать, современная ванная комната, оснащенная всеми необходимыми удобствами,
    а также рабочее пространство для выполнения деловых задач или планирования маршрута вашего отдыха.
    Мы предлагаем бесплатный Wi-Fi, телевизор с широким выбором каналов и доступ к прачечной услуге.
    Цена/сутки: 1500 рублей.
{% endblock %}

hostel/templates/hostel/room6.html
{% extends 'hostel/baseroom.html' %}
{% load static %}

{% block title %}
    Номер 6
{% endblock %}

{% block numberofroom %}
    Номер 6
{% endblock %}

{% block source %}
    <img src="{% static 'hostel/images/standart_room-1.jpg' %}" alt="Номер 9" style="height: 450px; border: 1px solid #1460af; border-radius: 8px;">
{% endblock %}

{% block description %}
    Добро пожаловать в наш стандартный номер! Это просторное и уютное помещение, созданное для вашего комфорта и отдыха.
    В стандартном номере вы найдете все необходимое для приятного пребывания.
    У нас предусмотрены удобная кровать, современная ванная комната, оснащенная всеми необходимыми удобствами,
    а также рабочее пространство для выполнения деловых задач или планирования маршрута вашего отдыха.
    Мы предлагаем бесплатный Wi-Fi, телевизор с широким выбором каналов и доступ к прачечной услуге.
    Цена/сутки: 1500 рублей.
{% endblock %}

hostel/templates/hostel/room7.html
{% extends 'hostel/baseroom.html' %}
{% load static %}

{% block title %}
    Номер 7
{% endblock %}

{% block numberofroom %}
    Номер 7
{% endblock %}

{% block source %}
    <img src="{% static 'hostel/images/standart_room-1.jpg' %}" alt="Номер 9" style="height: 450px; border: 1px solid #1460af; border-radius: 8px;">
{% endblock %}

{% block description %}
    Добро пожаловать в наш стандартный номер! Это просторное и уютное помещение, созданное для вашего комфорта и отдыха.
    В стандартном номере вы найдете все необходимое для приятного пребывания.
    У нас предусмотрены удобная кровать, современная ванная комната, оснащенная всеми необходимыми удобствами,
    а также рабочее пространство для выполнения деловых задач или планирования маршрута вашего отдыха.
    Мы предлагаем бесплатный Wi-Fi, телевизор с широким выбором каналов и доступ к прачечной услуге.
    Цена/сутки: 1500 рублей.
{% endblock %}

hostel/templates/hostel/room8.html
{% extends 'hostel/baseroom.html' %}
{% load static %}

{% block title %}
    Номер 8
{% endblock %}

{% block numberofroom %}
    Номер 8
{% endblock %}

{% block source %}
    <img src="{% static 'hostel/images/standart_room-1.jpg' %}" alt="Номер 9" style="height: 450px; border: 1px solid #1460af; border-radius: 8px;">
{% endblock %}

{% block description %}
    Добро пожаловать в наш стандартный номер! Это просторное и уютное помещение, созданное для вашего комфорта и отдыха.
    В стандартном номере вы найдете все необходимое для приятного пребывания.
    У нас предусмотрены удобная кровать, современная ванная комната, оснащенная всеми необходимыми удобствами,
    а также рабочее пространство для выполнения деловых задач или планирования маршрута вашего отдыха.
    Мы предлагаем бесплатный Wi-Fi, телевизор с широким выбором каналов и доступ к прачечной услуге.
    Цена/сутки: 1500 рублей.
{% endblock %}

hostel/templates/hostel/Бронирование.html
{% load static %}

<!DOCTYPE HTML>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <title>Бронирование</title>
  <style>
    body {
          background: #b6d5f6 fixed;
          background-size: cover;
      }

    .inline-block {
      display: inline-block;
    }

    table {
      width: 100%;
      font-size: 18px;
    }

    a.room-link:link{color: white; text-decoration: none}
    a.room-link:visited{color: white;}

    .room-button {
      padding: 10px 20px; /* Задает внутренний отступ кнопки */
      font-size: 16px; /* Задает размер шрифта кнопки */
      border-radius: 8px; /*Задает скругленные углы кнопки */
      color: #ffffff; /* Задает цвет текста кнопки */
    }

    .occupied {
    background-color: #FF000072;
    border: 2px solid #FF000072;
    }

    .free {
    background-color: #00800087;
    border: 2px solid #00800087;
    }

    a:link{color: #224588FF; text-decoration: none}
    a:visited{color: #224588FF;}

    a.menu-link:hover {
        background-color: #b6d5f6;
        border-radius: 3px;
    }
    a.menu-link:active {
        background-color: #6c90d3;
    }
  </style>
</head>
<body>

<header style="background-color: #d8ebff; border: 1px solid rgba(39,113,225,0.46); border-radius: 8px;">
    <div class="inline-block" style="position: relative; top: 6px; left: 10px">
        <img src="{% static 'hostel/images/vodoley.png' %}" height="100px" style="border-radius: 8px;">
    </div>


<h1 style="text-align: center; color: #224588FF; margin-top: -80px; font-family: Arial, sans-serif">ВОДОЛЕЙ</h1>

<div class="inline-block" style="margin-top: 5px; font-family: Arial, sans-serif">
  <a href="/" class="menu-link" style="margin-left: 550px;">Главная</a>
  <a href="/nomera" class="menu-link" >Номера</a>
  <a href="/vhod" class="menu-link" >Бронирование</a>
  <a href="/reg" class="menu-link" >Регистрация</a>
</div>

<hr color='5da4fc'>
</header>

<div style="margin-left: 140px; margin-top: 30px">
    {% for el in allrooms %}
    <button class="room-button {% if el.today_status == 'СВОБОДЕН' or el.tomorrow_status == 'СВОБОДЕН' %} free {% else %} occupied {% endif %}">
        <a class=room-link href="/room/{{el.number}}"> Номер {{el.number}}</a>
    </button>
{% endfor %}
</div>

<div class="inline-block" style="background-color: rgba(0,149,255,0.43); width: 900px; position: relative; left: 250px; top: 10px; border-radius: 8px; padding: 0 30px 0 30px;">
    <p style=" color: white; font-size: 16px; font-family: Arial, sans-serif">
        &#x1F4A1; Бронирование на сайте бесплатно. По этой причине бронирование возможно только на текущие и/или
        следущие сутки с момента бронирования. Заезд/Выезд – 08:00.
    </p>
</div>

<div style="margin-top: 50px;">
    <h2 style="text-align: center; margin-bottom: 10px; font-size: 20px; font-family: Arial, sans-serif; color: #224588">Планировка комнат</h2>
</div>
<div class="inline-block" style="background: rgb(121,168,225); margin-left: 400px; font-family: Arial, sans-serif">
    <table style="width: 600px; height: 300px; border: 2px solid #224588; border-collapse: collapse; border-radius: 8px; color: #224588">
        <tr>
            <td style="padding: 10px; border: 1px solid #224588; text-align: center;">1</td>
            <td style="padding: 10px; border: 1px solid #224588; text-align: center;">2</td>
            <td style="padding: 10px; border: 1px solid #224588; text-align: center;">3</td>
            <td style="padding: 10px; border: 1px solid #224588; text-align: center;">4</td>
            <td style="padding: 10px; border: 1px solid #224588; text-align: center;">5</td>
        </tr>
        <tr>
            <td colspan="5" align="center" style="padding: 10px; border: 1px solid #224588; background-color: rgb(196,216,250); font-weight: bold;">Коридор</td>
        </tr>
        <tr>
            <td style="padding: 10px; border: 1px solid #224588; text-align: center;">6</td>
            <td style="padding: 10px; border: 1px solid #224588; text-align: center;">7</td>
            <td style="padding: 10px; border: 1px solid #224588; text-align: center;">8</td>
            <td style="padding: 10px; border: 1px solid #224588; text-align: center;">9</td>
            <td style="padding: 10px; border: 1px solid #224588; text-align: center;">10</td>
        </tr>
    </table>
</div>


</body>
</html>

hostel/templates/hostel/Вход.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <title>Водолей</title>
   <style>
    body {
          background: #b6d5f6 fixed;
          background-size: cover;
      }

    .inline-block {
      display: inline-block;
    }

    a:link{color: #224588FF; text-decoration: none}
    a:visited{color: #224588FF;}

    a.menu-link:hover {
        background-color: #b6d5f6;
        border-radius: 3px;
    }
    a.menu-link:active {
        background-color: #6c90d3;
    }
   </style>
</head>
<body>

<header style="background-color: #d8ebff; border: 1px solid rgba(39,113,225,0.46); border-radius: 8px;">
    <div class="inline-block" style="position: relative; top: 6px; left: 10px">
        <img src="{% static 'hostel/images/vodoley.png' %}" height="100px" style="border-radius: 8px;">
    </div>


<h1 style="text-align: center; color: #224588FF; margin-top: -80px; font-family: Arial, sans-serif">ВОДОЛЕЙ</h1>

<div class="inline-block" style="margin-top: 5px; font-family: Arial, sans-serif">
  <a href="/" class="menu-link" style="margin-left: 550px;">Главная</a>
  <a href="/nomera" class="menu-link" >Номера</a>
  <a href="/vhod" class="menu-link" >Бронирование</a>
  <a href="/reg" class="menu-link" >Регистрация</a>
</div>

<hr color='5da4fc'>
</header>

<div style="text-align: center;">
  <h2>Вход</h2>
  <div style="background-color: rgba(0, 149, 255, 0.43); width: 400px; margin: 10px auto; border-radius: 8px; padding: 20px; font-family: Arial, sans-serif; color: white;">
    <p style="font-size: 16px;">
      &#x1F4A1; Перед бронированием необходмио зарегистрироваться и войти.
    </p>
  </div>
  <form method="post" style="display: inline-block; text-align: left; padding: 20px; border-radius: 8px; background-color: #d8ebff; border: 1px solid rgba(39, 113, 225, 0.46); font-family: Arial, sans-serif; color: #224588FF; margin-top: 20px;">
    {% csrf_token %}
    <label for="id_user_name">Имя пользователя:</label><br>
    {{ form.user_name }}<br><br>
    <label for="id_password">Пароль:</label><br>
    {{ form.password }}<br><br>
    <input type="submit" value="Войти" style="background-color: #224588FF; color: #fff; padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer; font-family: Arial, sans-serif;">
    <input type="reset" value="Очистить" style="background-color: #224588FF; color: #fff; padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer; font-family: Arial, sans-serif;">
  </form>
</div>



</body>
</html>

hostel/templates/hostel/Регистрация.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <title>Водолей</title>

   <style>
    body {
          background: #b6d5f6 fixed;
          background-size: cover;
      }

    .inline-block {
      display: inline-block;
    }

    a:link{color: #224588FF; text-decoration: none}
    a:visited{color: #224588FF;}

    a.menu-link:hover {
        background-color: #b6d5f6;
        border-radius: 3px;
    }
    a.menu-link:active {
        background-color: #6c90d3;
   </style>

    <script>
        function wshowMessage() {
            alert("Пользователь с таким логином уже существует!");
        }
        function gshowMessage() {
            alert("Регистрация прошла успешно!!");
        }
    </script>
</head>

<body>

<header style="background-color: #d8ebff; border: 1px solid rgba(39,113,225,0.46); border-radius: 8px;">
    <div class="inline-block" style="position: relative; top: 6px; left: 10px">
        <img src="{% static 'hostel/images/vodoley.png' %}" height="100px" style="border-radius: 8px;">
    </div>


<h1 style="text-align: center; color: #224588FF; margin-top: -80px; font-family: Arial, sans-serif">ВОДОЛЕЙ</h1>

<div class="inline-block" style="margin-top: 5px; font-family: Arial, sans-serif">
  <a href="/" class="menu-link" style="margin-left: 550px;">Главная</a>
  <a href="/nomera" class="menu-link" >Номера</a>
  <a href="/vhod" class="menu-link" >Бронирование</a>
  <a href="/reg" class="menu-link" >Регистрация</a>
</div>

<hr color='5da4fc'>
</header>

<div style="text-align: center; position: relative; top: 30px; font-family: Arial, sans-serif; color: #224588FF;">
    <h2>Регистрация</h2>
  <form method="post" style="display: inline-block; text-align: left; padding: 20px; border-radius: 8px; background-color: #d8ebff; border: 1px solid rgba(39, 113, 225, 0.46); ">
    {% csrf_token %}
    <label for="id_user_name">Имя пользователя:</label><br>
    {{ form.user_name }}<br><br>
    <label for="id_email">Почта (логин):</label><br>
    {{ form.email }}<br><br>
    <label for="id_password">Пароль:</label><br>
    {{ form.password }}<br><br>
    <input type="submit" value="Зарегистрироваться" style="background-color: #224588FF; color: #fff; padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer; font-family: Arial, sans-serif;">
    <input type="reset" value="Очистить" style="background-color: #224588FF; color: #fff; padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer; font-family: Arial, sans-serif;">
  </form>
</div>


{% if message %}
<script>
    {% if message == "Пользователь с таким логином уже существует!" %}
    alert("{{ message }}");
    {% elif message == "Регистрация прошла успешно!!" %}
    alert("{{ message }}");
    {% endif %}
</script>
{% endif %}

</body>
</html>